param(
    [string]$SavedVariablesPath = "D:\Games\Blizzard\World of Warcraft\_retail_\WTF\Account\<ACCOUNT>\SavedVariables\XIVEquip.lua",
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\tests\fixtures\live_capture.lua")
)

$ErrorActionPreference = "Stop"

function Find-MatchingBrace {
    param(
        [string]$Text,
        [int]$OpenIndex
    )

    $depth = 0
    $inString = $false
    $escape = $false

    for ($i = $OpenIndex; $i -lt $Text.Length; $i++) {
        $ch = $Text[$i]

        if ($inString) {
            if ($escape) {
                $escape = $false
            } elseif ($ch -eq "\") {
                $escape = $true
            } elseif ($ch -eq '"') {
                $inString = $false
            }
            continue
        }

        if ($ch -eq '"') {
            $inString = $true
            continue
        }

        if ($ch -eq "{") {
            $depth++
        } elseif ($ch -eq "}") {
            $depth--
            if ($depth -eq 0) {
                return $i
            }
        }
    }

    throw "Could not find the end of TestFixtures.LastCapture."
}

if (-not (Test-Path -LiteralPath $SavedVariablesPath)) {
    throw "SavedVariables file not found: $SavedVariablesPath"
}

$text = Get-Content -LiteralPath $SavedVariablesPath -Raw
$marker = '["LastCapture"]'
$markerIndex = $text.IndexOf($marker)
if ($markerIndex -lt 0) {
    throw "No XIVEquip_Settings.TestFixtures.LastCapture found. Run /xive fixture capture, then /reload or log out."
}

$openIndex = $text.IndexOf("{", $markerIndex)
if ($openIndex -lt 0) {
    throw "Found LastCapture marker, but no table body followed it."
}

$closeIndex = Find-MatchingBrace -Text $text -OpenIndex $openIndex
$fixture = $text.Substring($openIndex, $closeIndex - $openIndex + 1)

$fixture = [regex]::Replace($fixture, '(\["character"\]\s*=\s*\{(?:(?!\n\},).)*?\["name"\]\s*=\s*)"[^"]*"', '$1"<redacted>"', [System.Text.RegularExpressions.RegexOptions]::Singleline)
$fixture = [regex]::Replace($fixture, '(\["character"\]\s*=\s*\{(?:(?!\n\},).)*?\["realm"\]\s*=\s*)"[^"]*"', '$1"<redacted>"', [System.Text.RegularExpressions.RegexOptions]::Singleline)
$fixture = $fixture -replace '\s*\["guid"\]\s*=\s*"[^"]*",?\r?\n', "`n"

$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

@"
-- Generated by tools/import-fixture.ps1 from XIVEquip_Settings.TestFixtures.LastCapture.
-- Character name, realm, and item GUIDs are intentionally redacted.
return $fixture
"@ | Set-Content -LiteralPath $OutputPath

Write-Host "Fixture imported:" -ForegroundColor Green
Write-Host "  $OutputPath"
